// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVoSuYuQeZII9Q8gMtWr_6A4aMjeSkpMI',
    appId: '1:1053000975035:web:b26bc5b76da6cde298df9e',
    messagingSenderId: '1053000975035',
    projectId: 'mynotes-6544a',
    authDomain: 'mynotes-6544a.firebaseapp.com',
    storageBucket: 'mynotes-6544a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCx0cmzyCiJcxlQZY_uYbewSZqqXJolng',
    appId: '1:1053000975035:android:d24cd41d5e88064798df9e',
    messagingSenderId: '1053000975035',
    projectId: 'mynotes-6544a',
    storageBucket: 'mynotes-6544a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYHKZ_KiPbNCeLJ9400-4NOWpo-TFokc',
    appId: '1:1053000975035:ios:af80eb85e3a2056c98df9e',
    messagingSenderId: '1053000975035',
    projectId: 'mynotes-6544a',
    storageBucket: 'mynotes-6544a.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYHKZ_KiPbNCeLJ9400-4NOWpo-TFokc',
    appId: '1:1053000975035:ios:c90fd7bb89d2717198df9e',
    messagingSenderId: '1053000975035',
    projectId: 'mynotes-6544a',
    storageBucket: 'mynotes-6544a.appspot.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
